NAME    = ne
CMD_DIR = $(CURDIR)
SRCS    = $(CMD_DIR)/src/main.c \
          $(CMD_DIR)/src/conio.c \
          $(CMD_DIR)/src/fileio.c \
          $(CMD_DIR)/src/buffer.c \
          $(CMD_DIR)/src/editcore.c

include ../sdk/Makefile
